version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  phpdata:
    tty: true
    image: reallukemartin/drupal-php:0.0.3
    stdin_open: true
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:8005
      PHP_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
      - /var/www/html

  php:
    tty: true
    image: wodby/drupal-php:7.0-1.0.0
    stdin_open: true
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:8000
      PHP_DOCROOT: web
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    links:
      - phpdata
      - nginx
    labels:
      io.rancher.sidekicks: phpdata, nginx
    volumes_from:
      - phpdata

  nginx:
    tty: true
    image: wodby/drupal-nginx
    stdin_open: true
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: web
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    volumes_from:
      - phpdata
    ports:
      - "8000:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
